@startuml RemoveChannelUseCase

!include ../../../../config/config.puml


state INITIAL as "OPENED_CHANNELS"
state END as "OPENED_CHANNELS"
state 1 as " "
state 2 as " "
state 3 as " "

INITIAL --> 1 
note on link
Administrador solicita eliminar un canal
end note

1 --> 2 
note on link 
 <b>Sistema permite</b>
 * confirmar
 * cancelar
end note

2 -down[#red]-> END
note on link
cancelar
end note 

2 -down-> 3 
note on link
confirmar
end note 

3 -down-> END
note on link
<b>Sistema</b> 
* elimina el canal
end note 

@enduml

